name: BASIC CI
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: 3.10.12

jobs:
  ci-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v4

      - name: Set up Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v5  
        with:
          python-version: '${{env.PYTHON_VERSION}}'

      - name: Install dependencies
        run: |
          pip install -r Soft/requirements.txt
          pip install flake8

      - name: Run lint - flake8
        run: |
          # ignora:e E501 line too long
          flake8 . --ignore E501

      - name: Configure AWS Credentials
        if: always()
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
      
      - name: Set up AWS bucket
        if: always()
        run: |
          [ -d ~/s3-bucket ] || mkdir ~/s3-bucket
          sudo apt-get install -y s3fs
          s3fs satim-polsarpro ~/s3-bucket

      - name: Run tests
        if: always()
        working-directory: Soft/utils/
        run: |
          export GITHUB_RUNNER_CI=ON
          python test.py all

      - name: Copy test results
        if: always()
        run: |
          cp -Lpr ~/polsarpro/out/artifacts/ test-results
        shell: bash

      - name: Publish test report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'test-results/**/*.xml'

      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ~/polsarpro/out/artifacts/
      
      - name: Copy artifacts to AWS bucket
        if: always()
        run: |
          ls -alR ~/polsarpro/out/artifacts/
      #    cp ~/polsarpro/out/artifacts/ ~/s3-bucket
