name: MAIN CI
on:
  workflow_dispatch:
  #  push:
  #    branches: [main]
  #  pull_request:
  #    branches: [main]

env:
  PYTHON_VERSION: 3.10.12

jobs:
  ci-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v5  
        with:
          python-version: '${{env.PYTHON_VERSION}}'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: pip install -r Soft/requirements.txt

      - name: Install & run lint - flake8
        run: |
          pip install flake8
          # ignora:e E501 line too long
          flake8 . --ignore E501

      - name: Run tests
        working-directory: Soft/utils/
        run: python test.py all py

      - name: Copy Test Results
        if: always()
        run: |
          cp -Lpr ~/polsarpro/out/artifacts/ test-results
        shell: bash

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml

